name: ProfileUI
author: Infernus101
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13]
main: Infernus101\Main
version: 4.1.1
commands:
  profile:
    description: Player profile UI!
