name: ElixirStats
author: EmeraldMC
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13]
main: ElixirStats\Main
version: 1.0
commands:
  elixirstats:
    description: §7Check yours or others §dElixir§bHCF§r§7 stats
